// Generated by CoffeeScript 1.7.0
(function() {
  var EventEmitter, Harvest, ItemPile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  ItemPile = require('itempile');

  module.exports = function(game, opts) {
    return new Harvest(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-mine', 'voxel-registry', 'voxel-carry', 'voxel-inventory-hotbar']
  };

  Harvest = (function(_super) {
    __extends(Harvest, _super);

    function Harvest(game, opts) {
      var _ref, _ref1, _ref2, _ref3, _ref4;
      this.game = game;
      this.enableToolDamage = (_ref = opts.enableToolDamage) != null ? _ref : true;
      this.mine = (function() {
        var _ref2;
        if ((_ref1 = (_ref2 = game.plugins) != null ? _ref2.get('voxel-mine') : void 0) != null) {
          return _ref1;
        } else {
          throw new Error('voxel-harvest requires "voxel-mine" plugin');
        }
      })();
      this.registry = (function() {
        var _ref3;
        if ((_ref2 = (_ref3 = game.plugins) != null ? _ref3.get('voxel-registry') : void 0) != null) {
          return _ref2;
        } else {
          throw new Error('voxel-harvest requires "voxel-registry" plugin');
        }
      })();
      this.playerInventory = (function() {
        var _ref4, _ref5, _ref6;
        if ((_ref3 = (_ref4 = (_ref5 = game.plugins) != null ? (_ref6 = _ref5.get('voxel-carry')) != null ? _ref6.inventory : void 0 : void 0) != null ? _ref4 : opts.playerInventory) != null) {
          return _ref3;
        } else {
          throw new Error('voxel-harvest requires "voxel-carry" plugin or "playerInventory" option set to inventory instance');
        }
      })();
      this.hotbar = (_ref4 = game.plugins) != null ? _ref4.get('voxel-inventory-hotbar') : void 0;
      this.enable();
    }

    Harvest.prototype.enable = function() {
      return this.mine.on('break', this.onBreak = (function(_this) {
        return function(target) {
          var blockName, droppedPile, excess;
          game.setBlock(target.voxel, 0);
          _this.damageToolHeld(1);
          blockName = _this.registry.getBlockName(target.value);
          droppedPile = _this.block2ItemPile(blockName);
          if (droppedPile == null) {
            return;
          }
          excess = _this.playerInventory.give(droppedPile);
          if (excess > 0) {
            return _this.game.setBlock(target.voxel, target.value);
          }
        };
      })(this));
    };

    Harvest.prototype.disable = function() {
      return this.mine.removeListener('break', this.onBreak);
    };

    Harvest.prototype.damageToolHeld = function(n) {
      var maxDamage, tool, _base;
      if (n == null) {
        n = 1;
      }
      if (this.hotbar == null) {
        return;
      }
      if (!this.enableToolDamage) {
        return;
      }
      tool = this.hotbar.held();
      if (tool == null) {
        return;
      }
      maxDamage = this.registry.getProp(tool.item, 'maxDamage');
      if (maxDamage == null) {
        return;
      }
      if ((_base = tool.tags).damage == null) {
        _base.damage = 0;
      }
      tool.tags.damage += 1;
      if (tool.tags.damage >= maxDamage) {
        tool = void 0;
      }
      this.hotbar.inventory.set(this.hotbar.inventoryWindow.selectedIndex, tool);
      return this.hotbar.refresh();
    };

    Harvest.prototype.block2ItemPile = function(blockName) {
      var item, itemPile;
      item = this.registry.getProp(blockName, 'itemDrop');
      if (item === null) {
        return void 0;
      }
      if (item === void 0) {
        item = blockName;
      }
      itemPile = new ItemPile(item, 1);
      return itemPile;
    };

    return Harvest;

  })(EventEmitter);

}).call(this);
