// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter, Harvest, ItemPile,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = (require('events')).EventEmitter;

  ItemPile = require('ItemPile');

  module.exports = function(game, opts) {
    return new Harvest(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['mine', 'registry']
  };

  Harvest = (function(_super) {
    __extends(Harvest, _super);

    function Harvest(game, opts) {
      var _ref, _ref1, _ref2, _ref3;
      this.game = game;
      this.mine = (function() {
        var _ref1;
        if ((_ref = (_ref1 = game.plugins) != null ? _ref1.all.mine : void 0) != null) {
          return _ref;
        } else {
          throw 'voxel-harvest requires "voxel-mine" plugin';
        }
      })();
      this.registry = (function() {
        var _ref2;
        if ((_ref1 = (_ref2 = game.plugins) != null ? _ref2.all.registry : void 0) != null) {
          return _ref1;
        } else {
          throw 'voxel-harvest requires "voxel-mine" plugin';
        }
      })();
      this.playerInventory = (function() {
        if ((_ref2 = opts.playerInventory) != null) {
          return _ref2;
        } else {
          throw 'voxel-harvest requires "playerInventory" option set to inventory instance';
        }
      })();
      this.block2ItemPile = (_ref3 = opts.block2ItemPile) != null ? _ref3 : function(blockName) {
        return new ItemPile(blockName, 1);
      };
      this.enable();
    }

    Harvest.prototype.enable = function() {
      var _this = this;
      return this.mine.on('break', this.onBreak = function(target) {
        var blockName, droppedPile, excess;
        game.setBlock(target.voxel, 0);
        blockName = _this.registry.getBlockName(target.value);
        droppedPile = _this.block2ItemPile(blockName);
        if (droppedPile == null) {
          return;
        }
        excess = _this.playerInventory.give(droppedPile);
        if (excess > 0) {
          return _this.game.setBlock(target.voxel, target.value);
        }
      });
    };

    Harvest.prototype.disable = function() {
      return this.mine.removeListener('break', this.onBreak);
    };

    return Harvest;

  })(EventEmitter);

}).call(this);
